import csv
from collections import Counter

rows = []  # each: (domain, topic, subtopic, difficulty, source_text)

def add(domain, topic, subtopic, difficulty, text):
    rows.append((domain, topic, subtopic, difficulty, text))

# ================= ML (same 100 as before, now tagged domain='ml') =================
ml = [
("Linear Regression","Assumptions","easy","What are the key assumptions of ordinary least squares linear regression?"),
("Linear Regression","Assumptions","medium","What happens to your coefficient estimates and their interpretation if the homoscedasticity assumption is violated?"),
("Linear Regression","Multicollinearity","medium","How does multicollinearity affect linear regression coefficients, and how would you detect it?"),
("Linear Regression","Multicollinearity","medium","What is VIF (Variance Inflation Factor) and what threshold would make you worry about a feature?"),
("Linear Regression","Cost function","easy","Derive the closed-form (normal equation) solution for linear regression weights."),
("Linear Regression","Cost function","medium","Why is Mean Squared Error used as the loss function in OLS, and what probabilistic assumption justifies it?"),
("Linear Regression","Diagnostics","medium","How would you use residual plots to diagnose problems with a linear regression model?"),
("Linear Regression","Outliers","medium","How do outliers affect a linear regression fit, and what's the difference between leverage and influence?"),
("Linear Regression","Polynomial regression","medium","How does polynomial regression relate to linear regression, and what risk does increasing polynomial degree introduce?"),
("Linear Regression","R-squared","easy","What does R-squared measure, and why can it be misleading when comparing models with different numbers of features?"),
("Logistic Regression","Fundamentals","easy","Why can't we use linear regression directly for a binary classification problem?"),
("Logistic Regression","Fundamentals","easy","Explain the sigmoid function and why it's used in logistic regression."),
("Logistic Regression","Loss function","medium","Derive the log-loss (cross-entropy) cost function for logistic regression from maximum likelihood estimation."),
("Logistic Regression","Odds & interpretation","medium","How do you interpret a logistic regression coefficient in terms of odds ratio?"),
("Logistic Regression","Decision boundary","medium","Why is the decision boundary of logistic regression always linear, and how can you make it non-linear?"),
("Logistic Regression","Multiclass","medium","Explain the difference between One-vs-Rest and Softmax (multinomial) approaches for multiclass logistic regression."),
("Logistic Regression","Regularization","medium","How does L1 vs L2 regularization affect logistic regression coefficients differently?"),
("Logistic Regression","Threshold","easy","How does changing the classification threshold from 0.5 affect precision and recall?"),
("Logistic Regression","Class imbalance","medium","How would you handle a severely imbalanced dataset when training a logistic regression classifier?"),
("Logistic Regression","Assumptions","medium","What assumption does logistic regression make about the relationship between features and the log-odds of the outcome?"),
("Decision Trees","Splitting criteria","easy","Explain Gini impurity and entropy as splitting criteria for decision trees. When would they give different splits?"),
("Decision Trees","Splitting criteria","medium","Derive information gain and explain why it's used to choose the best feature to split on."),
("Decision Trees","Overfitting","medium","Why are decision trees prone to overfitting, and what techniques can control this?"),
("Decision Trees","Pruning","medium","Explain the difference between pre-pruning and post-pruning in decision trees."),
("Decision Trees","Categorical features","medium","How do decision trees handle categorical variables with high cardinality, and what problem can this cause?"),
("Decision Trees","Regression trees","medium","How does a regression tree decide on splits, and what criterion replaces Gini/entropy?"),
("Decision Trees","Bias-variance","medium","Where do decision trees sit on the bias-variance tradeoff, and how does tree depth affect this?"),
("Decision Trees","Missing values","medium","How can decision trees handle missing feature values during training and prediction?"),
("Decision Trees","Feature importance","medium","How is feature importance computed in a decision tree, and what's a limitation of this measure?"),
("Decision Trees","Comparison","easy","What are the main advantages and disadvantages of decision trees compared to linear models?"),
("SVM","Margin","easy","What is the maximum margin principle in Support Vector Machines?"),
("SVM","Support vectors","easy","What are support vectors, and why do only they matter for defining the decision boundary?"),
("SVM","Kernel trick","medium","Explain the kernel trick and why it allows SVMs to learn non-linear decision boundaries without explicitly computing high-dimensional features."),
("SVM","Kernel trick","hard","Derive why the RBF kernel corresponds to an infinite-dimensional feature space."),
("SVM","Soft margin","medium","What is the role of the C parameter in soft-margin SVM, and how does it affect bias-variance tradeoff?"),
("SVM","Dual formulation","hard","Why is the SVM optimization problem typically solved in its dual form rather than the primal form?"),
("SVM","Hinge loss","medium","What is hinge loss, and how does it differ from log-loss used in logistic regression?"),
("SVM","Multiclass","medium","How can SVMs, which are inherently binary classifiers, be extended to multiclass problems?"),
("SVM","Scaling","easy","Why is feature scaling important before training an SVM?"),
("SVM","Comparison","medium","In what scenarios would you prefer SVM over logistic regression, and vice versa?"),
("Ensemble Methods","Bagging","easy","Explain how Bagging reduces variance, and why Random Forest is a specific case of it."),
("Ensemble Methods","Random Forest","medium","How does Random Forest introduce additional randomness beyond bootstrap sampling used in bagging?"),
("Ensemble Methods","Boosting","medium","Explain the core idea behind boosting and how it differs fundamentally from bagging."),
("Ensemble Methods","AdaBoost","medium","Walk through how AdaBoost updates sample weights after each weak learner."),
("Ensemble Methods","Gradient Boosting","hard","Explain how Gradient Boosting fits new trees to the residuals/gradients of the loss function."),
("Ensemble Methods","XGBoost","medium","What key optimizations does XGBoost add over standard gradient boosting?"),
("Ensemble Methods","Bias-variance","medium","How do bagging and boosting differently affect bias and variance of the final ensemble?"),
("Ensemble Methods","Stacking","medium","Explain how stacking (stacked generalization) combines multiple base models, and what role the meta-learner plays."),
("Ensemble Methods","Out-of-bag","medium","What is out-of-bag (OOB) error in Random Forest, and why does it act as a free validation estimate?"),
("Ensemble Methods","Overfitting","medium","Can boosting overfit? Under what conditions, and how would you prevent it?"),
("Clustering","K-Means","easy","Explain the K-Means algorithm step by step, including how centroids are updated."),
("Clustering","K-Means","medium","Why is K-Means sensitive to initialization, and how does K-Means++ address this?"),
("Clustering","K selection","medium","Describe the elbow method and silhouette score for choosing the number of clusters K."),
("Clustering","K-Means limitations","medium","What assumptions does K-Means make about cluster shape, and when does it fail?"),
("Clustering","Hierarchical","medium","Explain the difference between agglomerative and divisive hierarchical clustering."),
("Clustering","Linkage","medium","Compare single-linkage, complete-linkage, and average-linkage in hierarchical clustering."),
("Clustering","DBSCAN","medium","Explain how DBSCAN defines clusters using core points, border points, and noise, and how it handles arbitrary cluster shapes."),
("Clustering","DBSCAN","medium","What are the eps and min_samples parameters in DBSCAN, and how do they affect clustering results?"),
("Clustering","Evaluation","medium","How would you evaluate clustering quality when you don't have ground truth labels?"),
("Clustering","Comparison","medium","When would you choose DBSCAN over K-Means, and what tradeoffs come with that choice?"),
("Dimensionality Reduction","PCA","easy","Explain the intuition behind Principal Component Analysis and what the principal components represent."),
("Dimensionality Reduction","PCA","medium","How are principal components computed using eigenvectors of the covariance matrix?"),
("Dimensionality Reduction","PCA","medium","Why is feature standardization important before applying PCA?"),
("Dimensionality Reduction","PCA","medium","How would you decide how many principal components to keep?"),
("Dimensionality Reduction","LDA","medium","How does Linear Discriminant Analysis differ from PCA in its objective?"),
("Dimensionality Reduction","t-SNE","medium","Explain how t-SNE preserves local structure when reducing dimensions for visualization."),
("Dimensionality Reduction","t-SNE","hard","Why can distances between clusters in a t-SNE plot be misleading, and what should you avoid concluding from them?"),
("Dimensionality Reduction","Curse of dimensionality","medium","What is the curse of dimensionality, and how does it affect distance-based algorithms like KNN?"),
("Dimensionality Reduction","Feature selection vs extraction","easy","What's the difference between feature selection and feature extraction as dimensionality reduction strategies?"),
("Dimensionality Reduction","SVD","hard","How does Singular Value Decomposition relate to PCA?"),
("Model Evaluation","Confusion matrix","easy","Explain precision, recall, and F1-score using a confusion matrix, and when each is most appropriate."),
("Model Evaluation","ROC-AUC","medium","What does the ROC curve plot, and how do you interpret AUC?"),
("Model Evaluation","ROC vs PR","medium","When would you prefer a Precision-Recall curve over an ROC curve?"),
("Model Evaluation","Cross-validation","easy","Explain k-fold cross-validation and why it gives a more reliable performance estimate than a single train-test split."),
("Model Evaluation","Stratified CV","medium","Why would you use stratified k-fold cross-validation instead of regular k-fold for a classification problem?"),
("Model Evaluation","Data leakage","medium","What is data leakage in model evaluation, and give an example of how it can silently inflate performance metrics."),
("Model Evaluation","Regression metrics","easy","Compare MAE, MSE, and RMSE as regression evaluation metrics, and when you'd choose one over another."),
("Model Evaluation","Class imbalance metrics","medium","Why is accuracy a misleading metric for imbalanced classification problems, and what would you use instead?"),
("Model Evaluation","Calibration","hard","What does it mean for a classifier's predicted probabilities to be well-calibrated, and how would you check this?"),
("Model Evaluation","Statistical significance","hard","How would you determine whether one model's performance improvement over another is statistically significant?"),
("Regularization","Bias-variance tradeoff","easy","Explain the bias-variance tradeoff and how it relates to underfitting and overfitting."),
("Regularization","L1 vs L2","medium","Compare L1 (Lasso) and L2 (Ridge) regularization, and explain why L1 tends to produce sparse solutions."),
("Regularization","Elastic Net","medium","What problem does Elastic Net solve by combining L1 and L2 penalties?"),
("Regularization","Regularization strength","medium","How does increasing the regularization strength (lambda) affect model bias and variance?"),
("Regularization","Dropout","medium","Even though dropout is a deep learning technique, explain the general regularization principle it embodies."),
("Regularization","Early stopping","medium","How does early stopping act as a form of regularization?"),
("Regularization","Cross-validation for hyperparams","medium","How would you use cross-validation to select the optimal regularization strength for a model?"),
("Regularization","Ridge derivation","hard","Derive the closed-form solution for Ridge regression and explain why it's always invertible unlike plain OLS."),
("Regularization","Overfitting signs","easy","What signs in training vs validation loss curves indicate that a model is overfitting?"),
("Regularization","Feature scaling","medium","Why is feature scaling important when applying L1/L2 regularization?"),
("Probability & Statistics","Bayes theorem","easy","State Bayes' theorem and explain how it underlies the Naive Bayes classifier."),
("Probability & Statistics","Naive Bayes","medium","Why is the 'naive' independence assumption in Naive Bayes often violated in practice, yet the classifier still performs well?"),
("Probability & Statistics","MLE vs MAP","hard","Explain the difference between Maximum Likelihood Estimation and Maximum A Posteriori estimation."),
("Probability & Statistics","Central Limit Theorem","medium","State the Central Limit Theorem and explain its practical relevance in machine learning and statistics."),
("Probability & Statistics","p-values","medium","What is a p-value, and what is a common misinterpretation of it?"),
("Probability & Statistics","A/B testing","medium","Design an A/B test to evaluate whether a new recommendation algorithm improves click-through rate, and describe how you'd determine significance."),
("Probability & Statistics","Correlation vs causation","easy","Why does correlation not imply causation, and how might this mislead feature selection?"),
("Probability & Statistics","Expectation & variance","easy","Define expectation and variance of a random variable, and explain how variance relates to model stability."),
("Probability & Statistics","Sampling bias","medium","What is sampling bias, and how could it affect a trained model's real-world performance?"),
("Probability & Statistics","Distributions","medium","Why might you choose a Poisson distribution over a Normal distribution when modeling count data?"),
]
for topic, subtopic, diff, text in ml:
    add("ml", topic, subtopic, diff, text)

# ================= DL (50) =================
dl = [
("Neural Network Basics","Perceptron","easy","Explain how a single perceptron computes its output and why it can only learn linearly separable functions."),
("Neural Network Basics","Activation functions","easy","Why are non-linear activation functions necessary in neural networks?"),
("Neural Network Basics","Activation functions","medium","Compare ReLU, sigmoid, and tanh — what problems does ReLU solve that sigmoid/tanh have?"),
("Neural Network Basics","Activation functions","medium","What is the dying ReLU problem, and how do Leaky ReLU or ELU address it?"),
("Neural Network Basics","Forward pass","easy","Walk through the forward pass computation of a simple 2-layer feedforward network."),
("Backpropagation","Chain rule","medium","Explain how backpropagation uses the chain rule to compute gradients layer by layer."),
("Backpropagation","Vanishing gradients","medium","What causes the vanishing gradient problem in deep networks, and how does it relate to activation function choice?"),
("Backpropagation","Exploding gradients","medium","What causes exploding gradients, and what techniques (e.g. gradient clipping) mitigate them?"),
("Backpropagation","Weight initialization","medium","Why does weight initialization matter, and how do Xavier/He initialization address vanishing/exploding gradients?"),
("Optimization","SGD variants","easy","Explain the difference between batch, mini-batch, and stochastic gradient descent."),
("Optimization","Momentum","medium","How does momentum help gradient descent escape shallow local minima or navigate ravines?"),
("Optimization","Adam","medium","Explain how Adam combines momentum and adaptive learning rates from RMSProp."),
("Optimization","Learning rate","medium","What happens if the learning rate is too high vs too low, and what is learning rate scheduling?"),
("Regularization (DL)","Dropout","medium","Explain how dropout works during training vs inference, and why it acts as an implicit ensemble."),
("Regularization (DL)","Batch normalization","medium","Explain what batch normalization does and why it helps training stability and speed."),
("Regularization (DL)","Weight decay","easy","How does weight decay (L2) act as regularization in a neural network's loss function?"),
("Regularization (DL)","Early stopping","easy","Why is early stopping considered a regularization technique in deep learning?"),
("CNNs","Convolution operation","easy","Explain how a convolution operation works over an image, including stride and padding."),
("CNNs","Convolution operation","medium","Why do CNNs use shared weights (filters) instead of fully connected layers for images?"),
("CNNs","Pooling","easy","What is the purpose of pooling layers (max/average pooling) in a CNN?"),
("CNNs","Receptive field","medium","What is the receptive field of a CNN neuron, and how does stacking layers increase it?"),
("CNNs","Architectures","medium","What key innovation did ResNet introduce, and what problem does it solve in very deep networks?"),
("CNNs","Parameter count","medium","How would you calculate the number of parameters in a convolutional layer given kernel size, input/output channels?"),
("RNNs","Fundamentals","easy","Explain how a vanilla RNN processes a sequence and maintains a hidden state."),
("RNNs","Vanishing gradients","medium","Why do vanilla RNNs struggle with long-range dependencies?"),
("RNNs","LSTM","medium","Explain the roles of the forget, input, and output gates in an LSTM cell."),
("RNNs","GRU","medium","How does a GRU simplify the LSTM architecture, and what tradeoffs does this involve?"),
("RNNs","Bidirectional","easy","What is a bidirectional RNN, and when would you use one over a unidirectional RNN?"),
("Transformers","Self-attention","medium","Explain how self-attention computes a weighted combination of tokens using queries, keys, and values."),
("Transformers","Self-attention","hard","Why is the scaling factor (sqrt(d_k)) used in scaled dot-product attention?"),
("Transformers","Multi-head attention","medium","Why do transformers use multiple attention heads instead of a single attention mechanism?"),
("Transformers","Positional encoding","medium","Why do transformers need positional encodings, and how do sinusoidal encodings work?"),
("Transformers","Architecture","medium","Compare the encoder-only, decoder-only, and encoder-decoder transformer architectures with examples of each."),
("Transformers","Comparison to RNNs","medium","Why do transformers parallelize better than RNNs during training?"),
("Training Deep Nets","Overfitting signs","easy","What signs during training indicate a deep network is overfitting versus underfitting?"),
("Training Deep Nets","Data augmentation","easy","Why does data augmentation help generalization, and give two examples for image data."),
("Training Deep Nets","Transfer learning","medium","Explain the difference between feature extraction and fine-tuning in transfer learning."),
("Training Deep Nets","Loss functions","medium","Why is cross-entropy loss typically preferred over MSE for classification tasks in deep learning?"),
("Training Deep Nets","Hyperparameter tuning","medium","What hyperparameters matter most when tuning a deep neural network, and how would you prioritize search?"),
("Autoencoders","Fundamentals","easy","Explain the encoder-decoder structure of an autoencoder and what it's typically used for."),
("Autoencoders","Variational Autoencoders","hard","How does a VAE differ from a standard autoencoder in terms of the latent space it learns?"),
("GANs","Fundamentals","medium","Explain the adversarial training setup between a generator and discriminator in a GAN."),
("GANs","Training instability","hard","Why are GANs notoriously difficult to train, and what is mode collapse?"),
("Normalization","Batch vs Layer norm","medium","Compare batch normalization and layer normalization, and explain why transformers use layer norm."),
("Embeddings","Word embeddings","easy","What problem do word embeddings (like word2vec) solve compared to one-hot encoding words?"),
("Embeddings","Word2Vec","medium","Explain the difference between the CBOW and Skip-gram approaches in Word2Vec."),
("Computer Vision","Object detection","medium","At a high level, how do object detection models differ from image classification models in what they predict?"),
("Computer Vision","Transfer learning in CV","easy","Why is it common to use a pretrained ImageNet backbone for a new vision task with limited data?"),
("Sequence Models","Seq2Seq","medium","Explain the encoder-decoder architecture used in sequence-to-sequence models for tasks like translation."),
("Sequence Models","Attention in Seq2Seq","medium","What problem does attention solve in encoder-decoder models compared to using a single fixed context vector?"),
("Model Efficiency","Model compression","medium","Briefly explain pruning, quantization, and knowledge distillation as techniques to make deep models smaller/faster."),
]
for topic, subtopic, diff, text in dl:
    add("dl", topic, subtopic, diff, text)

# ================= GenAI (40) =================
genai = [
("LLM Fundamentals","Tokenization","easy","What is tokenization in the context of LLMs, and why do models use subword tokenization (e.g. BPE) instead of whole words?"),
("LLM Fundamentals","Autoregressive generation","easy","Explain how an autoregressive language model generates text one token at a time."),
("LLM Fundamentals","Context window","medium","What is a context window, and what are the practical consequences of it being too small for a task?"),
("LLM Fundamentals","Scaling laws","medium","What do LLM scaling laws describe about the relationship between model size, data, and compute?"),
("Transformer Internals","Attention recap","medium","Why is self-attention central to why transformer-based LLMs can model long-range dependencies?"),
("Transformer Internals","KV cache","hard","What is a KV cache, and why does it make autoregressive generation faster after the first token?"),
("Training LLMs","Pretraining objective","easy","What is the next-token-prediction objective used to pretrain most LLMs?"),
("Training LLMs","Fine-tuning","medium","What is the difference between full fine-tuning and parameter-efficient fine-tuning (e.g. LoRA)?"),
("Training LLMs","RLHF","medium","Explain at a high level how RLHF (Reinforcement Learning from Human Feedback) aligns a base LLM to be more helpful/safe."),
("Training LLMs","Instruction tuning","medium","What is instruction tuning, and how does it differ from RLHF?"),
("Prompting","Zero-shot vs few-shot","easy","What's the difference between zero-shot and few-shot prompting, and when would few-shot help?"),
("Prompting","Chain-of-thought","medium","How does chain-of-thought prompting improve performance on multi-step reasoning tasks?"),
("Prompting","Prompt injection","medium","What is a prompt injection attack, and why is it a security concern for LLM applications?"),
("Embeddings & Retrieval","Text embeddings","easy","What do text embeddings represent, and why are they useful for semantic search?"),
("Embeddings & Retrieval","Similarity metrics","easy","Why is cosine similarity commonly used to compare text embeddings rather than Euclidean distance?"),
("RAG","Fundamentals","easy","Explain the core idea of Retrieval-Augmented Generation and what problem it solves compared to relying on the LLM's parametric knowledge alone."),
("RAG","Chunking","medium","Why does chunk size and overlap matter when preparing documents for a RAG pipeline?"),
("RAG","Retrieval quality","medium","What can go wrong in a RAG pipeline if the retriever returns irrelevant chunks, and how does that affect the generated answer?"),
("RAG","Hybrid search","medium","What is hybrid search (combining keyword/BM25 with vector search), and why might it outperform pure vector search?"),
("RAG","Re-ranking","medium","What role does a re-ranker play in a RAG pipeline after initial retrieval?"),
("Vector Databases","Fundamentals","easy","What problem do vector databases solve that traditional relational databases are not designed for?"),
("Vector Databases","ANN search","medium","What is Approximate Nearest Neighbor (ANN) search, and why is it used instead of exact nearest neighbor search at scale?"),
("Vector Databases","Indexing","hard","At a high level, how does an HNSW index enable fast approximate nearest neighbor search?"),
("Agents","Fundamentals","medium","What distinguishes an 'LLM agent' from a plain LLM completing a single prompt?"),
("Agents","Tool use","medium","How do LLM agents decide when and how to call an external tool or function?"),
("Agents","ReAct pattern","medium","Explain the ReAct (Reason + Act) pattern for LLM agents."),
("Hallucination","Definition","easy","What is hallucination in the context of LLMs, and why does it happen even in well-trained models?"),
("Hallucination","Mitigation","medium","What are two practical techniques to reduce hallucination in an LLM-based application?"),
("Evaluation","LLM output evaluation","medium","Why is evaluating LLM-generated text harder than evaluating a traditional classifier's output?"),
("Evaluation","LLM-as-judge","medium","What is the 'LLM-as-judge' evaluation approach, and what's a risk of using it?"),
("Fine-tuning Methods","LoRA","hard","Explain how LoRA reduces the number of trainable parameters during fine-tuning by using low-rank matrices."),
("Fine-tuning Methods","Quantization","medium","What is quantization (e.g. 8-bit, 4-bit) in the context of deploying LLMs, and what's the tradeoff?"),
("Safety & Alignment","Alignment problem","easy","What does 'alignment' mean in the context of large language models?"),
("Safety & Alignment","Guardrails","medium","What are guardrails in an LLM application, and give an example of an input-side and output-side guardrail."),
("Multimodal Models","Fundamentals","medium","What does it mean for a model to be multimodal, and how do vision-language models typically combine image and text inputs?"),
("Cost & Latency","Inference cost","easy","What factors drive the inference cost of running an LLM (e.g. model size, context length, output length)?"),
("Cost & Latency","Streaming","easy","Why do most LLM applications stream tokens back to the user instead of waiting for the full response?"),
("Function Calling","Fundamentals","medium","How does structured function calling let an LLM reliably trigger external actions instead of relying on free-text parsing?"),
("Context Management","Long context handling","medium","What challenges arise when trying to fit large documents into an LLM's context window, and how does RAG address this differently from just using a bigger context window?"),
("Embeddings & Retrieval","Embedding model choice","medium","What factors would you consider when choosing an embedding model for a RAG system (e.g. dimensionality, domain fit, cost)?"),
]
for topic, subtopic, diff, text in genai:
    add("genai", topic, subtopic, diff, text)

# ================= Big Data (50) =================
bigdata = [
("Hadoop/HDFS","Architecture","easy","Explain the roles of the NameNode and DataNodes in HDFS architecture."),
("Hadoop/HDFS","Block storage","easy","Why does HDFS split files into large fixed-size blocks (e.g. 128MB), and how does replication provide fault tolerance?"),
("Hadoop/HDFS","Fault tolerance","medium","What happens in HDFS when a DataNode fails, and how does the NameNode detect and recover from it?"),
("Hadoop/HDFS","MapReduce","medium","Explain the Map and Reduce phases of the MapReduce programming model with a simple word-count example."),
("Hadoop/HDFS","MapReduce","medium","What is a combiner in MapReduce, and how does it reduce network shuffle overhead?"),
("Spark Fundamentals","RDDs","easy","What is a Resilient Distributed Dataset (RDD), and what does 'resilient' refer to?"),
("Spark Fundamentals","Lazy evaluation","medium","Why does Spark use lazy evaluation for transformations, and how does this differ from actions?"),
("Spark Fundamentals","DAG scheduler","medium","How does Spark's DAG scheduler use the lineage of transformations to plan and recover computation?"),
("Spark Fundamentals","Transformations vs actions","easy","Give two examples each of Spark transformations and actions, and explain the distinction."),
("Spark Architecture","Driver & executors","medium","Explain the roles of the driver program, cluster manager, and executors in a Spark application."),
("Spark Architecture","Partitioning","medium","Why does partitioning matter for Spark job performance, and what problems arise from too few or too many partitions?"),
("Spark Architecture","Shuffle","medium","What is a shuffle in Spark, and why is it typically the most expensive operation in a job?"),
("Spark Performance","Catalyst optimizer","medium","At a high level, what does Spark's Catalyst optimizer do for DataFrame/SQL queries?"),
("Spark Performance","Caching/persistence","easy","When would you use .cache() or .persist() in Spark, and what's the tradeoff?"),
("Spark Performance","Skew","medium","What is data skew in a distributed Spark job, and how can it hurt performance?"),
("Spark Performance","Broadcast joins","medium","What is a broadcast join in Spark, and when is it appropriate to use one?"),
("Spark Streaming","Structured Streaming","medium","How does Spark Structured Streaming model a stream as an unbounded table?"),
("Spark Streaming","Micro-batching","medium","Explain micro-batch processing and how it differs from true event-at-a-time stream processing."),
("Spark Streaming","Watermarking","hard","What is watermarking in structured streaming, and what problem does it solve with late-arriving data?"),
("Kafka Fundamentals","Topics & partitions","easy","Explain the relationship between Kafka topics, partitions, and how partitioning enables parallelism."),
("Kafka Fundamentals","Producers & consumers","easy","How do Kafka consumer groups enable multiple consumers to process a topic's messages in parallel without duplication?"),
("Kafka Fundamentals","Offsets","medium","What is a consumer offset in Kafka, and how does it enable at-least-once or exactly-once processing semantics?"),
("Kafka Architecture","Replication","medium","How does Kafka use leader/follower replication across brokers to provide fault tolerance?"),
("Kafka Architecture","Durability","medium","What role does the write-ahead log (commit log) play in Kafka's durability guarantees?"),
("Kafka Delivery Semantics","At-least-once vs exactly-once","hard","Explain the difference between at-most-once, at-least-once, and exactly-once delivery semantics in Kafka."),
("Kafka Delivery Semantics","Idempotent producers","medium","How do idempotent producers in Kafka help avoid duplicate messages on retries?"),
("Airflow","DAGs","easy","What is a DAG in Airflow, and why must it be acyclic?"),
("Airflow","Scheduling","medium","How does Airflow's scheduler decide when to trigger a DAG run, and what's the difference between schedule interval and execution date?"),
("Airflow","Operators","easy","What is an Airflow operator, and give two examples of built-in operator types."),
("Airflow","Retries & failure handling","medium","How would you configure retries and alerting in an Airflow task to handle transient failures gracefully?"),
("Airflow","Backfilling","medium","What does backfilling mean in Airflow, and when would you need it?"),
("Hive","Fundamentals","easy","What is Hive, and how does it let you query data stored in HDFS using SQL-like syntax?"),
("Hive","Execution engine","medium","How does Hive translate a HiveQL query into MapReduce or Spark jobs under the hood?"),
("Hive","Partitioning & bucketing","medium","Explain the difference between partitioning and bucketing in Hive, and when you'd use each."),
("Hive","External vs managed tables","medium","What's the difference between an external table and a managed table in Hive, particularly around data lifecycle?"),
("Data Modeling","Star schema","medium","Explain the star schema data model and why fact/dimension table separation is useful in a data warehouse."),
("Data Modeling","Batch vs streaming","easy","What are the key tradeoffs between batch processing and stream processing for a data pipeline?"),
("Data Modeling","Lambda architecture","medium","What is the Lambda architecture, and what problem does it try to solve by combining batch and speed layers?"),
("Data Modeling","Data lake vs warehouse","easy","What's the difference between a data lake and a data warehouse, and when would you use each?"),
("File Formats","Parquet vs CSV","medium","Why is Parquet generally preferred over CSV for large-scale analytical workloads?"),
("File Formats","Columnar storage","medium","Why does columnar storage improve performance for analytical (OLAP) queries compared to row-based storage?"),
("Distributed Systems Concepts","CAP theorem","medium","Explain the CAP theorem and how it forces tradeoffs in distributed data systems."),
("Distributed Systems Concepts","Consistency models","hard","What's the difference between strong consistency and eventual consistency, and give an example system that favors each."),
("Distributed Systems Concepts","Fault tolerance","medium","How do most big data systems (HDFS, Kafka, Spark) achieve fault tolerance despite running on unreliable commodity hardware?"),
("Pipeline Design","Idempotency","medium","Why is idempotency an important property for data pipeline tasks that might be retried?"),
("Pipeline Design","Schema evolution","medium","What challenges does schema evolution (e.g. adding/removing fields) create in a long-running data pipeline, and how do formats like Avro/Parquet help?"),
("Pipeline Design","Data quality checks","easy","What kinds of data quality checks would you build into a pipeline before data reaches a downstream consumer?"),
("Resource Management","YARN","medium","What role does YARN play in a Hadoop ecosystem, and how does it decouple resource management from MapReduce?"),
("Resource Management","Cluster sizing","medium","What factors would you consider when sizing a Spark cluster for a given workload (executors, cores, memory)?"),
("Monitoring","Pipeline observability","easy","What kinds of metrics/logs would you monitor to know a data pipeline is healthy versus silently failing?"),
]
for topic, subtopic, diff, text in bigdata:
    add("bigdata", topic, subtopic, diff, text)

# ================= DBMS (40) — conceptual, complements the existing schema-based prep doc =================
dbms = [
("Relational Model","Fundamentals","easy","What is a relational database, and what do keys (primary, foreign, candidate) represent conceptually?"),
("Normalization","1NF-3NF","easy","Explain 1NF, 2NF, and 3NF with the kind of anomaly each one eliminates."),
("Normalization","BCNF","medium","How does BCNF differ from 3NF, and give an example of a relation that satisfies 3NF but not BCNF."),
("Normalization","Denormalization","medium","Why might you deliberately denormalize a schema, and what do you trade off by doing so?"),
("Transactions","ACID","easy","Explain the four ACID properties of database transactions."),
("Transactions","Isolation levels","medium","Compare Read Uncommitted, Read Committed, Repeatable Read, and Serializable isolation levels — what anomaly does each prevent?"),
("Transactions","Dirty reads","medium","What is a dirty read, and which isolation level prevents it?"),
("Transactions","Phantom reads","medium","What is a phantom read, and how does it differ from a non-repeatable read?"),
("Concurrency Control","Locking","medium","Explain the difference between shared (read) locks and exclusive (write) locks."),
("Concurrency Control","Deadlocks","medium","What causes a deadlock in a database, and how do systems typically detect or prevent it?"),
("Concurrency Control","MVCC","hard","Explain how Multi-Version Concurrency Control (MVCC) allows readers and writers to avoid blocking each other."),
("Indexing","B-Tree index","medium","Explain how a B-Tree index speeds up lookups, and why it's well suited to range queries."),
("Indexing","Clustered vs non-clustered","medium","What's the difference between a clustered and non-clustered index, and how many clustered indexes can a table have?"),
("Indexing","When not to index","medium","When could adding an index hurt performance rather than help it?"),
("Indexing","Composite indexes","medium","How does column order matter in a composite (multi-column) index?"),
("Query Execution","Query planner","medium","What role does a query optimizer/planner play in executing a SQL query, and what is an execution plan?"),
("Query Execution","Joins","easy","Compare inner join, left join, and full outer join with what rows each includes."),
("Query Execution","Join algorithms","hard","Explain at a high level how nested loop join, hash join, and merge join differ in approach."),
("Query Execution","EXPLAIN","medium","What would you look for in a query's EXPLAIN output to diagnose a slow query?"),
("SQL Fundamentals","Aggregate functions","easy","Explain the difference between WHERE and HAVING clauses in a SQL query with aggregation."),
("SQL Fundamentals","Window functions","medium","What do window functions let you do that a plain GROUP BY cannot?"),
("SQL Fundamentals","Subqueries vs joins","medium","When would you use a correlated subquery instead of a join, and what's the performance implication?"),
("SQL Fundamentals","NULL handling","easy","How does SQL's three-valued logic (TRUE/FALSE/UNKNOWN) affect comparisons involving NULL?"),
("Constraints","Foreign keys","easy","What does a foreign key constraint enforce, and what happens on delete/update with CASCADE vs RESTRICT?"),
("Constraints","Unique vs primary key","easy","What's the difference between a UNIQUE constraint and a PRIMARY KEY constraint?"),
("NoSQL vs SQL","When to choose NoSQL","medium","What factors would push you toward a NoSQL database instead of a relational one for a given application?"),
("NoSQL vs SQL","Document vs key-value vs column-family","medium","Briefly distinguish document stores, key-value stores, and wide-column stores with an example database for each."),
("Replication","Master-replica","medium","How does master-replica (primary-secondary) database replication work, and what's the risk of reading from a replica?"),
("Replication","Synchronous vs asynchronous","medium","What's the tradeoff between synchronous and asynchronous replication in terms of consistency vs latency?"),
("Sharding","Fundamentals","medium","What is database sharding, and what problem does it solve that a single larger machine can't?"),
("Sharding","Shard key selection","hard","What makes a good sharding key, and what problems arise from a poorly chosen one?"),
("Backup & Recovery","WAL","medium","What is a Write-Ahead Log, and how does it help a database recover after a crash?"),
("Backup & Recovery","Point-in-time recovery","medium","What is point-in-time recovery, and what does a database need (e.g. WAL archives) to support it?"),
("Performance Tuning","N+1 problem","medium","What is the N+1 query problem in an application layer, and how would you fix it?"),
("Performance Tuning","Connection pooling","easy","Why is connection pooling important for an application talking to a relational database?"),
("Schema Design","One-to-many vs many-to-many","easy","How do you model a many-to-many relationship in a relational schema?"),
("Schema Design","Soft deletes","medium","What is a soft delete pattern, and what tradeoffs does it introduce compared to a hard delete?"),
("Views","Fundamentals","easy","What is a database view, and how does a materialized view differ from a regular view?"),
("Stored Procedures","Fundamentals","easy","What are stored procedures, and what's a tradeoff of putting business logic in the database versus the application layer?"),
("Transactions","Distributed transactions","hard","What challenges arise when a transaction spans multiple databases or services, and what is two-phase commit trying to solve?"),
("Query Execution","Query caching","medium","How does query result caching interact with data freshness, and when might it cause stale reads?"),
]
for topic, subtopic, diff, text in dbms:
    add("dbms", topic, subtopic, diff, text)

# ================= DSA — concepts, not coding problems (40) =================
dsa = [
("Complexity Analysis","Big-O","easy","Explain what Big-O notation represents and why constant factors are ignored."),
("Complexity Analysis","Time vs space","easy","What's the difference between time complexity and space complexity, and give an example of a time-space tradeoff."),
("Complexity Analysis","Amortized analysis","medium","What does amortized time complexity mean, using dynamic array resizing as an example."),
("Arrays","Fundamentals","easy","What are the time complexities of access, insertion, and deletion in an array, and why?"),
("Arrays","Dynamic arrays","medium","How does a dynamic array (like Python's list) grow when it runs out of capacity, and why is this typically amortized O(1) for appends?"),
("Linked Lists","Fundamentals","easy","Compare singly and doubly linked lists in terms of memory overhead and operations supported."),
("Linked Lists","Arrays vs linked lists","medium","When would you prefer a linked list over an array, and vice versa?"),
("Stacks & Queues","Fundamentals","easy","Explain the LIFO vs FIFO behavior of stacks and queues with a real-world use case for each."),
("Stacks & Queues","Implementation","medium","How can you implement a queue using two stacks?"),
("Hash Tables","Fundamentals","easy","Explain how a hash table achieves average O(1) lookup, insertion, and deletion."),
("Hash Tables","Collisions","medium","Compare chaining and open addressing as collision resolution strategies in hash tables."),
("Hash Tables","Load factor","medium","What is a hash table's load factor, and why does it trigger a resize when it gets too high?"),
("Trees","Binary trees","easy","What's the difference between a binary tree and a binary search tree?"),
("Trees","BST operations","medium","Explain the time complexity of search, insert, and delete in a BST, and why it degrades to O(n) in the worst case."),
("Trees","Balanced trees","medium","Why do self-balancing trees like AVL or Red-Black trees exist, and what property do they maintain?"),
("Trees","Tree traversals","easy","Explain the difference between in-order, pre-order, and post-order tree traversal."),
("Heaps","Fundamentals","easy","What is a heap, and how does it differ from a binary search tree?"),
("Heaps","Heap operations","medium","Explain how insertion and extract-min/max work in a binary heap, and why both are O(log n)."),
("Heaps","Use cases","medium","Why is a heap the natural data structure for implementing a priority queue?"),
("Graphs","Representations","easy","Compare adjacency matrix and adjacency list representations of a graph in terms of space and typical use case."),
("Graphs","BFS","medium","Explain how BFS works and why it finds the shortest path in an unweighted graph."),
("Graphs","DFS","medium","Explain how DFS works, and give a problem it's naturally suited for (e.g. cycle detection, topological sort)."),
("Graphs","Dijkstra's algorithm","hard","Explain how Dijkstra's algorithm finds shortest paths in a weighted graph, and why it fails with negative edge weights."),
("Graphs","Topological sort","medium","What is topological sort, and what property must a graph have for it to be possible?"),
("Sorting","Comparison sorts","medium","Compare the time complexity and stability of merge sort, quicksort, and heapsort."),
("Sorting","Quicksort worst case","medium","Why does quicksort degrade to O(n^2) in the worst case, and how does randomized pivot selection help?"),
("Sorting","Stability","easy","What does it mean for a sorting algorithm to be 'stable', and why might that matter?"),
("Searching","Binary search","easy","Explain how binary search works and why it requires a sorted array."),
("Searching","Binary search variants","medium","How would you modify binary search to find the first or last occurrence of a target in a sorted array with duplicates?"),
("Dynamic Programming","Fundamentals","medium","What two properties (overlapping subproblems, optimal substructure) make a problem suitable for dynamic programming?"),
("Dynamic Programming","Memoization vs tabulation","medium","Compare top-down memoization and bottom-up tabulation as DP implementation strategies."),
("Dynamic Programming","Classic example","medium","Explain how DP solves the 0/1 knapsack problem, including what the recurrence relation looks like conceptually."),
("Greedy Algorithms","Fundamentals","medium","What is a greedy algorithm, and why doesn't the greedy approach always yield an optimal solution?"),
("Greedy Algorithms","When greedy works","medium","What property must a problem have for a greedy algorithm to guarantee an optimal solution?"),
("Recursion","Fundamentals","easy","What are the two essential components every correct recursive function needs?"),
("Recursion","Recursion vs iteration","medium","What's the tradeoff between a recursive and iterative solution to the same problem, particularly around stack space?"),
("Tries","Fundamentals","medium","What is a trie, and why is it well suited for prefix-based string search (e.g. autocomplete)?"),
("Union-Find","Fundamentals","hard","Explain how the union-find (disjoint set) data structure with path compression and union by rank achieves near-constant time operations."),
("Sliding Window","Fundamentals","medium","What is the sliding window technique, and what kind of problems does it typically optimize from O(n^2) to O(n)?"),
("Two Pointers","Fundamentals","medium","Explain the two-pointer technique and give a problem type it's commonly used to solve."),
]
for topic, subtopic, diff, text in dsa:
    add("dsa", topic, subtopic, diff, text)

# ================= Python (30) =================
python = [
("Core Language","Mutable vs immutable","easy","Explain the difference between mutable and immutable objects in Python, with examples."),
("Core Language","Variable scope","easy","Explain Python's LEGB rule for variable scope resolution."),
("Core Language","*args/**kwargs","easy","What do *args and **kwargs let a function do, and how do they differ from each other?"),
("Core Language","Decorators","medium","Explain what a decorator does in Python and write out the conceptual steps of how one wraps a function."),
("Core Language","Generators","medium","What's the difference between a generator and a regular function, and why are generators memory-efficient?"),
("Core Language","Context managers","medium","What does the `with` statement do, and how does a context manager implement __enter__/__exit__?"),
("Core Language","List vs tuple","easy","When would you choose a tuple over a list, beyond just mutability?"),
("Core Language","Shallow vs deep copy","medium","Explain the difference between a shallow copy and a deep copy of a nested data structure."),
("Data Structures","Dict internals","medium","How does a Python dict achieve average O(1) lookup, and what changed about dict ordering in Python 3.7+?"),
("Data Structures","Set operations","easy","What are the time complexities of membership testing in a Python list versus a set, and why?"),
("Data Structures","Comprehensions","easy","Why are list comprehensions generally preferred over equivalent for-loops in Python for simple transformations?"),
("Memory Management","Garbage collection","medium","How does Python's reference counting garbage collector work, and what problem do cyclic references create?"),
("Memory Management","GIL","medium","What is the Global Interpreter Lock (GIL), and why does it limit true parallelism for CPU-bound multithreaded Python code?"),
("Concurrency","Threading vs multiprocessing","medium","When would you use multiprocessing instead of threading in Python, given the GIL?"),
("Concurrency","asyncio","medium","What problem does asyncio solve, and how does it differ from threading for I/O-bound concurrency?"),
("OOP","Classes vs instances","easy","Explain the difference between a class attribute and an instance attribute."),
("OOP","Inheritance","easy","What is method resolution order (MRO) in Python, and why does it matter with multiple inheritance?"),
("OOP","Magic methods","medium","What do dunder methods like __init__, __repr__, and __eq__ let you customize about a class's behavior?"),
("OOP","Property decorator","medium","What does the @property decorator let you do, and why would you use it instead of a plain attribute?"),
("Error Handling","Exceptions","easy","Explain the try/except/else/finally control flow and when each block executes."),
("Error Handling","Custom exceptions","easy","Why would you define a custom exception class instead of raising a generic Exception?"),
("Functional Style","Map/filter/lambda","easy","What do map(), filter(), and lambda let you express, and when is a list comprehension more readable instead?"),
("Functional Style","Closures","medium","What is a closure in Python, and how does a nested function 'remember' variables from its enclosing scope?"),
("Iterators","Iterator protocol","medium","What methods must an object implement to satisfy Python's iterator protocol?"),
("Type System","Duck typing","easy","What does 'duck typing' mean in Python, and how does it relate to Python being dynamically typed?"),
("Type System","Type hints","easy","What do type hints provide in Python given that the language remains dynamically typed at runtime?"),
("Performance","Profiling","medium","How would you identify the performance bottleneck in a slow Python script?"),
("Performance","Common pitfalls","medium","Why is repeated string concatenation with + in a loop inefficient in Python, and what's a better alternative?"),
("Modules & Packaging","Virtual environments","easy","Why are virtual environments used in Python projects, and what problem do they solve?"),
("Modules & Packaging","__init__.py","easy","What role does __init__.py play in a Python package?"),
]
for topic, subtopic, diff, text in python:
    add("python", topic, subtopic, diff, text)

# ---------------- write per-domain CSVs ----------------
by_domain = {}
for domain, topic, subtopic, diff, text in rows:
    by_domain.setdefault(domain, []).append((domain, topic, subtopic, diff, text))

for domain, domain_rows in by_domain.items():
    fname = f"{domain}_questions_seed.csv"
    with open(fname, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["domain", "topic", "subtopic", "difficulty", "source_text"])
        writer.writerows(domain_rows)
    print(f"{fname}: {len(domain_rows)} questions")

print("\nTotal questions:", len(rows))
print(Counter(r[0] for r in rows))